ToysSalesWebIU/Areas/Admin/Controllers/CategoryController.cs
using AutoMapper;
using Business.Dtos.Categories;
using Business.Repositories.InterfaceRepo;
using Data.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace ToysSalesWebIU.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepo;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CategoryController(ICategoryRepository categoryRepo,IMapper mapper,IWebHostEnvironment webHostEnvironment)
        {
            _categoryRepo = categoryRepo;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await _categoryRepo.GetAllAsync();
            return View(categories);
        }

        [HttpGet]
        public IActionResult CreateCategory() => View();

        [HttpPost]
        public async Task<IActionResult> CreateCategory(CreateCategoryDTO model)
        {
            if (ModelState.IsValid)
            {
                if (await _categoryRepo.AnyCategoryName(model.Name))
                {
                    TempData["Warning"] = "Bu kategori ismi zaten var.";
                    return View(model);
                }

                string imageName = "noimage.png";
                if (model.UploadImage != null)
                {

                    string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "images/categories");
                    imageName = $"{Guid.NewGuid().ToString()}_{model.UploadImage.FileName}";
                    string filePath = Path.Combine(uploadDir, imageName);
                    FileStream fileStream = new FileStream(filePath, FileMode.Create);
                    await model.UploadImage.CopyToAsync(fileStream);
                    fileStream.Close();
                }

                var category = _mapper.Map<Category>(model);
                category.Image = imageName;
                await _categoryRepo.AddAsync(category);
                TempData["Success"] = "Kategori oluşturuldu!";
                return RedirectToAction("Index");
            }
            TempData["Error"] = "Kategori oluşturulamadı!!";
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCategory(int id)
        {
            if (id > 0)
            {
                var category = await _categoryRepo.GetByIdAsync(id);
                if (category != null)
                {
                    var model = _mapper.Map<UpdateCategoryDTO>(category);
                    return View(model);
                }
                TempData["Error"] = "Kategori bulunamadı!!";
                return View();
            }
            TempData["Error"] = "Hatalı işlem!!";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCategory(UpdateCategoryDTO model)
        {
            if (ModelState.IsValid)
            {
                if (await _categoryRepo.AnyCategoryName(model.Name))
                {
                    TempData["Warning"] = "Bu kategori adı zaten kullanılıyor!!";
                    return View(model);
                }

                string imageName = "noimage.png";
                if (model.UploadImage != null)
                {
                    string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "images/categories");
                    imageName = $"{Guid.NewGuid().ToString()}_{model.UploadImage.FileName}";
                    string filePath = Path.Combine(uploadDir, imageName);
                    FileStream fileStream = new FileStream(filePath, FileMode.Create);
                    await model.UploadImage.CopyToAsync(fileStream);
                    fileStream.Close();

                }

                var category = _mapper.Map<Category>(model);
                category.Image = imageName;
                await _categoryRepo.UpdateAsync(category);
                TempData["Success"] = "Kategori güncellendi!!";
                return RedirectToAction("Index");
            }
            TempData["Error"] = "Kategori güncellenemedi!!";
            return View(model);
        }

        public async Task<IActionResult> DeleteCategory(int id)
        {
            if (id > 0)
            {
                var category = await _categoryRepo.GetByIdAsync(id);
                if (category != null)
                {
                    await _categoryRepo.DeleteAsync(category);
                    TempData["Success"] = "Kategori silindi!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Success"] = "Kategori bulunamadı!!";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Warning"] = "Hatalı işlem!!";
            }
            return RedirectToAction("Index");


        }
    }
}

ToysSalesWebIU/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace ToysSalesWebIU.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ToysSalesWebIU/Areas/Admin/Controllers/ProductController.cs
using AutoMapper;
using Business.Dtos.Products;
using Business.Repositories.InterfaceRepo;
using Data.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;

namespace ToysSalesWebIU.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepo;
        private readonly IMapper _mapper;
        private readonly ICategoryRepository _categoryRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IProductRepository productRepo,IMapper mapper,ICategoryRepository categoryRepo,IWebHostEnvironment webHostEnvironment)
        {
            _productRepo = productRepo;
            _mapper = mapper;
            _categoryRepo = categoryRepo;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            var products=await _productRepo.GetAllAsync();
            return View(products);
        }

        [HttpGet]
        public async Task<IActionResult> CreateProduct() 
        {
            ViewBag.Categories = new SelectList
                (
                await _categoryRepo.GetAllAsync(), "Id", "Name"
                );
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(CreateProductDTO model)
        {
            if (ModelState.IsValid) 
            {
                string imageName = "noimage.png";
                if (model.UploadImage != null)
                {
                    
                    string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "images/products");
                    imageName = $"{Guid.NewGuid().ToString()}_{model.UploadImage.FileName}";
                    string filePath = Path.Combine(uploadDir, imageName);
                    FileStream fileStream = new FileStream(filePath, FileMode.Create);
                    await model.UploadImage.CopyToAsync(fileStream);
                    fileStream.Close();
                }

                var product = _mapper.Map<Product>(model);
                product.Image = imageName;
                await _productRepo.AddAsync(product);
                TempData["Success"] = "Ürün kaydedildi!!";
                return RedirectToAction("Index");
            }
            TempData["Error"] = "Ürün kaydedilemedi!!";
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProduct(int id)
        {
            var product=await _productRepo.GetByIdAsync(id);
            UpdateProductDTO model = new UpdateProductDTO()
            {
                Name = product.Name,
                Description = product.Description,
                UnitPrice = product.UnitPrice,
                UnitStock = product.UnitStock,
                Image = product.Image,
                CategoryId = product.CategoryId,
                Categories = await _categoryRepo.GetAllAsync()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(UpdateProductDTO model)
        {
            if (ModelState.IsValid)
            {
                string imageName = "noimage.png";
                if (model.UploadImage != null)
                {

                    string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "images/products");
                    imageName = $"{Guid.NewGuid().ToString()}_{model.UploadImage.FileName}";
                    string filePath = Path.Combine(uploadDir, imageName);
                    FileStream fileStream = new FileStream(filePath, FileMode.Create);
                    await model.UploadImage.CopyToAsync(fileStream);
                    fileStream.Close();
                }

                var product=_mapper.Map<Product>(model);
                product.Image = imageName;
                await _productRepo.UpdateAsync(product);
                TempData["Success"] = "Ürün Güncellendi";
                return RedirectToAction("Index");

            }
            TempData["Error"] = "Ürün Güncellenemedi";
            return View(model);
        }

    }
}

ToysSalesWebIU/Areas/Admin/Controllers/RolesController.cs
using Business.Dtos.Roles;
using Data.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ToysSalesWebIU.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "admin")]
	public class RolesController : Controller
	{
		private readonly UserManager<AppUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;

		public RolesController(UserManager<AppUser> userManager,RoleManager<IdentityRole> roleManager)
		{
			_userManager = userManager;
			_roleManager = roleManager;
		}
		public IActionResult Index()
		{
			var roles = _roleManager.Roles;
			return View(roles);
		}

		[HttpGet]
		public IActionResult CreateRole() 
		{
			return View();
		}

		[HttpPost,ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateRole(CreateRoleDTO model)
		{
			if (ModelState.IsValid)
			{
				IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(model.Name));

				if (result.Succeeded)
				{
					TempData["Success"] = "Rol Kaydedildi";
					return RedirectToAction("Index");
				}
				else 
				{
					foreach (IdentityError error in result.Errors)
					{
						ModelState.AddModelError("", error.Description);
					}
				}
			}

			TempData["Error"] = "Rol Kaydedilemedi";
			return View(model);

		}

		[HttpGet]
		public async Task<IActionResult> AssignedUser(string id)
		{
			IdentityRole role =await _roleManager.FindByIdAsync(id);

			List<AppUser> hasRole= new List<AppUser>();
			List<AppUser> hasNotRole = new List<AppUser>();

			foreach (AppUser user in _userManager.Users)
			{
				var list = await _userManager.IsInRoleAsync(user, role.Name) ? hasRole : hasNotRole;
				list.Add(user);
			}

			AssignedUserDTO model = new AssignedUserDTO()
			{
				Role = role,
				HasRole = hasRole,
				HasNotRole = hasNotRole,
				RoleName = role.Name,
			};
			return View(model);
		}

		[HttpPost,ValidateAntiForgeryToken]
		public async Task<IActionResult> AssignedUser(AssignedUserDTO model)
		{
			IdentityResult result;
			foreach (var userId in model.AddIds ?? new string[] {})
			{
				AppUser user = await _userManager.FindByIdAsync(userId);
				result = await _userManager.AddToRoleAsync(user, model.RoleName);
			}
			foreach (var userId in model.DeleteIds ?? new string[] { })
			{
				AppUser user = await _userManager.FindByIdAsync(userId);
				result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
			}

			return RedirectToAction("Index");
		}

		public async Task<IActionResult> DeleteRole(string id) 
		{
			var role =await _roleManager.FindByIdAsync(id);

			IdentityResult result=await _roleManager.DeleteAsync(role);

			if (result.Succeeded)
			{
				TempData["Succuess"] = "Role Silindi";
			}
			foreach (IdentityError error in result.Errors)
			{
				ModelState.AddModelError("", error.Description);
				TempData["error"] = error.Description;
			}
			return RedirectToAction("index");
		}
	}
}

ToysSalesWebIU/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modernize Free</title>
    <link rel="shortcut icon" type="image/png" href="~/src/assets/images/logos/favicon.png" />
    <link rel="stylesheet" href="~/src/assets/css/styles.min.css" />
</head>

<body>
    <!--  Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed">
        <!-- Sidebar Start -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div>
                <div class="brand-logo d-flex align-items-center justify-content-between">
                    <a href="./index.html" class="text-nowrap logo-img">
                        <img src="~/src/assets/images/logos/dark-logo.svg" width="180" alt="" />
                    </a>
                    <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                        <i class="ti ti-x fs-8"></i>
                    </div>
                </div>
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
                    <ul id="sidebarnav">
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">Home</span>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" aria-expanded="false" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                                <span>
                                    <i class="ti ti-layout-dashboard"></i>
                                </span>
                                <span class="hide-menu">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">Menü</span>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" aria-expanded="false" asp-area="Admin" asp-controller="Category" asp-action="Index">
                                <span>
                                    <i class="ti ti-article"></i>
                                </span>
                                <span class="hide-menu">Categoriler</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" aria-expanded="false" asp-area="Admin" asp-controller="Product" asp-action="Index">
                                <span>
                                    <i class="ti ti-alert-circle"></i>
                                </span>
                                <span class="hide-menu">Ürünler</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" aria-expanded="false" asp-area="Admin" asp-controller="Roles" asp-action="Index">
                                <span>
                                    <i class="ti ti-cards"></i>
                                </span>
                                <span class="hide-menu">Roller</span>
                            </a>
                        </li>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!--  Sidebar End -->
        <!--  Main wrapper -->
        <div class="body-wrapper mb-3">
            <!--  Header Start -->
            <header class="app-header">
                <nav class="navbar navbar-expand-lg navbar-light">

                    <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                        <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                            <li class="nav-item dropdown">
                                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    <img src="~/src/assets/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                                    <div class="message-body">
                                        <a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-outline-primary mx-3 mt-2 d-block">Ana Sayfa</a>
                                    </div>
                                    <div class="message-body">
                                        <a asp-area="" asp-controller="Account" asp-action="LogOut" class="btn btn-outline-primary mx-3 mt-2 d-block">Çıkış</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!--  Header End -->
        </div>

        <div class="container mt-3">
            <main role="main" class="pb-3">
                <partial name="_NotPartial" />
                @RenderBody()
            </main>
        </div>

    </div>
    <script src="~/src/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/src/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/src/assets/js/sidebarmenu.js"></script>
    <script src="~/src/assets/js/app.min.js"></script>
    <script src="~/src/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/src/assets/libs/simplebar/dist/simplebar.js"></script>
    <script src="~/src/assets/js/dashboard.js"></script>
</body>

</html>

ToysSalesWebIU/Areas/Admin/Views/Shared/_NotPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification" role="alert">
        @TempData["Success"]
    </div>
}

@if (TempData["Warning"] != null)
{
    <div class="alert alert-warning notification" role="alert">
        @TempData["Warning"]
    </div>
}

@if (TempData["Danger"] != null)
{
    <div class="alert alert-danger notification" role="alert">
        @TempData["Danger"]
    </div>
}